load("@rules_cc//cc:defs.bzl", "cc_library")

exports_files(["math_utils.cpp", "math_utils.h"])

cc_library(
    name = "math_utils",
    srcs = ["math_utils.cpp"],
    hdrs = ["math_utils.h"],
    visibility = ["//visibility:public"],
)
