name: Bazel ADAS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Static Analysis Tools (cppcheck)
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Cache Bazel builds
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Run Tests & MISRA Analysis
      # This command finds all sh_test, cc_test, etc. and runs them!
      run: bazel test //... --test_output=errors

    - name: Build ADAS Application
      run: bazel build //...

    - name: Upload ADAS Executable
      uses: actions/upload-artifact@v4
      with:
        name: adas-release-binary
        path: bazel-bin/adas/adas_app
        retention-days: 7

    - name: Publish to GitHub Releases
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: ADAS Release build-${{ github.run_number }}
        files: bazel-bin/adas/adas_app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
